packages:
  - apps/*

catalog:
  '@types/node': ^24.2.0
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  react: 19.1.1
  react-dom: 19.1.1
  tailwind-merge: 2.6.0
  tailwindcss: ^4.1.11
  typescript: ~5.8.3
  vite: ^7.0.4
