packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.2.0
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@hookform/resolvers': ^3.10.0
  '@phosphor-icons/web': ^2.1.0
  '@radix-ui/react-popover': ^1.1.2
  '@radix-ui/react-select': ^2.1.2
  '@radix-ui/react-slot': ^1.1.0
  '@radix-ui/react-tabs': ^1.1.1
  '@react-spring/web': ^9.7.4
  '@tanstack/react-query': ^5.59.0
  '@vitejs/plugin-react-swc': ^4.2.0
  '@eslint/js': ^9.15.0
  'eslint': ^9.15.0
  'eslint-plugin-react': ^7.37.2
  'eslint-plugin-react-hooks': ^5.0.0
  'eslint-plugin-react-refresh': ^0.4.14
  'globals': ^15.12.0
  'jiti': ^1.21.7
  'typescript-eslint': ^8.15.0
  'axios': ^1.7.7
  'class-variance-authority': 0.7.1
  'clsx': 2.1.1
  'lottie-web': ^5.12.2
  'react': 19.1.1
  'react-dom': 19.1.1
  'react-hook-form': ^7.53.2
  'react-joyride': ^2.5.2
  'tailwind-merge': 2.6.0
  'tailwindcss': ^4.1.11
  'typescript': ~5.8.3
  'vite': ^7.0.4
  'zod': ^3.23.8
