packages:
  - 'apps/*'

# Configurações globais do PNPM
catalog:
  # React ecosystem
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  
  # Build tools
  typescript: ~5.8.3
  vite: ^7.0.4
  '@types/node': ^24.2.0
  
  # Styling
  tailwindcss: ^4.1.11
  
  # Utilities
  clsx: ^2.0.0
  class-variance-authority: ^0.7.0
  tailwind-merge: ^2.0.0