packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.15.0
  '@hookform/resolvers': ^3.10.0
  '@phosphor-icons/web': 2.1.2
  '@radix-ui/react-accordion': ^1.2.2
  '@radix-ui/react-alert-dialog': ^1.1.3
  '@radix-ui/react-avatar': ^1.1.2
  '@radix-ui/react-checkbox': ^1.1.3
  '@radix-ui/react-dialog': ^1.1.3
  '@radix-ui/react-dropdown-menu': ^2.1.3
  '@radix-ui/react-label': ^2.1.1
  '@radix-ui/react-popover': ^1.1.2
  '@radix-ui/react-scroll-area': ^1.2.2
  '@radix-ui/react-select': ^2.1.2
  '@radix-ui/react-separator': ^1.1.1
  '@radix-ui/react-slot': ^1.1.0
  '@radix-ui/react-switch': ^1.1.2
  '@radix-ui/react-tabs': ^1.1.1
  '@radix-ui/react-toast': ^1.2.3
  '@radix-ui/react-tooltip': ^1.1.5
  '@react-spring/web': ^9.7.4
  '@tanstack/react-query': ^5.59.0
  '@tanstack/react-query-devtools': ^5.59.0
  '@tanstack/react-router': ^1.133.0
  '@tanstack/react-router-devtools': ^1.133.0
  '@tanstack/react-table': ^8.21.0
  '@tanstack/router-plugin': ^1.133.0
  '@types/d3': ^7.4.3
  '@types/node': ^24.2.0
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react-swc': ^4.2.0
  autoprefixer: ^10.4.20
  axios: ^1.7.7
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  d3: ^7.9.0
  date-fns: ^4.1.0
  eslint: ^9.15.0
  eslint-plugin-react: ^7.37.2
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.14
  globals: ^15.12.0
  jiti: ^1.21.7
  lottie-web: ^5.12.2
  lucide-react: ^0.468.0
  postcss: ^8.5.1
  react: 19.1.1
  react-dom: 19.1.1
  react-hook-form: ^7.53.2
  react-joyride: ^2.5.2
  react-spring: ^10.0.3
  recharts: ^3.3.0
  tailwind-merge: 2.6.0
  tailwindcss: ^4.1.11
  tailwindcss-animate: ^1.0.7
  typescript: ~5.8.3
  typescript-eslint: ^8.15.0
  vite: ^7.0.4
  vite-plugin-compression: ^0.5.1
  zod: ^3.23.8
